apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-uploads-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.patientUploads }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-uploads-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.doctorUploads }}
