apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.secrets.db.username | quote }}
  password: {{ .Values.secrets.db.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.app.jwtSecret | quote }}
  refresh-token-secret: {{ .Values.secrets.app.refreshTokenSecret | quote }}
  internal-service-key: {{ .Values.secrets.app.internalServiceKey | quote }}
  smsapi-token: {{ .Values.secrets.app.smsApiToken | quote }}
  smsapi-sender-id: {{ .Values.secrets.app.smsSenderId | quote }}
  stripe-secret-key: {{ .Values.secrets.app.stripeSecretKey | quote }}
  stripe-webhook-secret: {{ .Values.secrets.app.stripeWebhookSecret | quote }}
  gemini-api-key: {{ .Values.secrets.app.geminiApiKey | quote }}
